site_name: 'Agustín Aguilera Conti | @aagustinconti'
site_description: 'As a recent graduate with a degree in Telecommunications Engineering, I combine my technical experience in telecommunications with a growing interest in Data Science, Machine Learning, and DevOps. I possess proficient skills in Python and system management, along with a solid understanding of IP networks. I am a proactive learner, eager to expand my skills and experiences. I have demonstrated exceptional teamwork and responsibility, and I am keen to contribute to innovative projects while absorbing knowledge from experienced professionals.' 
site_author: 
site_keywords: 'MLOps, Machine Learning, DevOps, Engineer, Engineering, Telecommunications'
extra:
  meta:
    author: 'Agustín Aguilera Conti | @aagustinconti'
    description: 'As a recent graduate with a degree in Telecommunications Engineering, I combine my technical experience in telecommunications with a growing interest in Data Science, Machine Learning, and DevOps. I possess proficient skills in Python and system management, along with a solid understanding of IP networks. I am a proactive learner, eager to expand my skills and experiences. I have demonstrated exceptional teamwork and responsibility, and I am keen to contribute to innovative projects while absorbing knowledge from experienced professionals.'
    keywords: 'MLOps, Machine Learning, DevOps, Engineer, Engineering, Telecommunications'
site_url: https://aagustinconti.com.ar
repo_url: https://github.com/aagustinconti/my_personal_page
repo_name: aagustinconti/my_personal_page
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  favicon: img/favicon.ico
  logo: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  
  language: en
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aagustinconti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aagustinconti/
  analytics:
    provider: google
    property: G-BJGHMZR328

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/aagustinconti"  target="_blank" rel="noopener">Agustin Aguilera Conti</a>
